### ISSUE TITLE
Add number of results returned to search results

### ISSUE THREAD

**Issue by ClaraCogswell** [cznethub/cznet-discovery#26]
**Describe the feature you'd like and what it will do**
When a search is completed on the discovery portal, the number of results found is not presented. In a search interface,  It is common for the page to also indicate how many results the search has returned. Our search results page should display the number of results the search returned under the search bar. This feature would align with our goal of demonstrating how many resources have been contributed by teh cznet, and just generally be useful. 

**Why is this feature important?**
Additional data about the data in our system is always useful. It is also an easy way to see how many results meet certain filter criteria. 

**Additional context**
![Screen Shot 2023-05-11 at 8 51 46 AM](https://github.com/cznethub/cznet-discovery/assets/90924476/3b2b3bcb-db57-479d-81d4-f975ca66b569)

Like this

**Comment by horsburgh** [comment]
Deployed and working on production, so closing.

<img width="1078" alt="image" src="https://github.com/user-attachments/assets/3c81bca3-d1bb-4aca-adf6-89b6af2b6b2c">
