### ISSUE TITLE
Add "CZ Project" filter to search results page

### ISSUE THREAD

**Issue by horsburgh** [cznethub/cznet-discovery#6]
**Describe the feature you'd like and what it will do**

The search results page needs a "CZ Project" filter that provides the ability for users to select one or more CZ projects for filtering results. 
* Users should be able to select multiple projects. 
* Search results will be limited to those resources in the catalog that are affiliated with the selected project(s). 
* The list of projects should include the 9 CZNet thematic cluster projects and the legacy CZO projects.

**Why is this feature important?**
A short description of the importance of this feature and what it will help you achieve.

This will make it easy for users to isolate cataloged resources associated with one or more CZ projects.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].

Nope. Feature request.

**Additional context**

NA

**Comment by Maurier** [comment]
This filter has been added.
