### ISSUE TITLE
Improve typeahead search terms

### ISSUE THREAD

**Issue by horsburgh** [cznethub/cznet-discovery#7]
**Describe the feature you'd like and what it will do**

The current implementation of typeahead search term generation creates some odd terms. I think this is related to things like special characters that appear in resource titles, etc. that probably need to be handled so that suggested terms make more sense. Example screen shots of weirdness below. I'm calling this a feature request rather than a bug because I suspect that it requires enhancing existing functionality rather than really being a bug.

**Why is this feature important?**
A short description of the importance of this feature and what it will help you achieve.

Users should be presented with useful typeahead terms and not gibberish.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].

Some typeahead suggestions don't make sense.

**Additional context**

See the 3rd and 5th terms in the following screen shot:

<img width="891" alt="image" src="https://user-images.githubusercontent.com/3485902/208760662-7f59482f-13c8-4306-b4da-bd3c5195f2ca.png">

See multiple weird terms in the following screen shot:

<img width="831" alt="image" src="https://user-images.githubusercontent.com/3485902/208760802-f3b50370-82b1-4497-a531-f905e03741f5.png">

**Comment by Maurier** [comment]
We consulted with the Atlas team on how to improve our typeahead and these are the takeaways:

- [x] Store a copy of the query fields that is suitable for typeahead.
  - [x] Need a clean up strategy describing transformations to the data to be stored.
    - [x] @sblack-usu to export a JS file with a list of documents showing only typeahead fields: `keywords`, `name`, and `description`.
  - [x] Use the data for the typeahead only. Achieved through Atlas 'triggers'.
- [x]  Performance improvements by removing GraphQL layer.
- [ ] ~Follow up with Atlas team about bug when using autocomplete + wildcard search inside a compound clause.~

**Comment by sblack-usu** [comment]
Sanitizing the discover name, description and keywords for typeahead is configured and demonstrated on beta.  There may be some tweaks done to the sanitize function as testing continues.

**Comment by horsburgh** [comment]
@Maurier and @sblack-usu - is this now implemented and can it be closed?

**Comment by Maurier** [comment]
Correct. These improvements have been implemented as planned and we are happy with the results for now. Closing.
