### ISSUE TITLE
Enable content type filter

### ISSUE THREAD

**Issue by horsburgh** [cznethub/cznet-discovery#9]
**Describe the feature you'd like and what it will do**

The search results page has a "Content type" filter that I think right now only works with resources with a content type of "Dataset". If we are going to have this filter, it needs to respond to other content types. Or, if we are unable to filter by content type because the metadata do not support this functionality, that filter needs to be removed from the search results page.

**Why is this feature important?**
A short description of the importance of this feature and what it will help you achieve.

It would be nice to be able to filter resources by content type.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].

The current "Content type" filter on the search results page is only partially functional.

**Additional context**

<img width="353" alt="image" src="https://user-images.githubusercontent.com/3485902/208762315-332298c0-9a80-401f-8066-5566019558fb.png">

**Comment by Maurier** [comment]
This is actually working correctly, but our database only has records with content type 'Dataset'. Assigning to @sblack-usu in case we can add more data to our database.

**Comment by sblack-usu** [comment]
We currently do not have metadata to filter by content type, everything is assumed to be a dataset.  We should go ahead and remove this filter unless there are plans to introduce the other content types.

**Comment by martinseul** [comment]
I was under the impression we'd be adding functionality to enable content type filtering. It might not be needed in a first release but I think it's a common filter option users are interested in.

**Comment by sblack-usu** [comment]
The functionality already exists, the metadata does not.  As @horsburgh requested in the description the filter should be used or removed.

**Comment by martinseul** [comment]
sorry,  wrong wording we should add the datatype information to the metadata to enable the existing functionality to work correctly.

**Comment by horsburgh** [comment]
For first public release, I think we can hide or remove this filter. We should look into what it would take to add content type metadata so we could enable the filter. HydroShare may be the only repository that has the concept of content type.

**Comment by sblack-usu** [comment]
@Maurier - can I reassign this to you?  Looks like the filter needs to be removed/hidden for now.

**Comment by Maurier** [comment]
Yes, I should be able to do it.

**Comment by Maurier** [comment]
Filter has been hidden for now. Relevant discussion can continue on https://github.com/cznethub/cznet-discovery/issues/17
